// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace WukongGameplayTags
{
	LEGENDOFWUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	LEGENDOFWUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	LEGENDOFWUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	LEGENDOFWUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Pad);
	LEGENDOFWUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	
	LEGENDOFWUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Attack);
	LEGENDOFWUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LockOn);

	LEGENDOFWUKONG_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Jump);
	
}
